import Head from 'next/head';
import Link from 'next/link';
import Style from '../styles/card.module.css';

import { Roboto, Karla } from 'next/font/google';
import { prisma } from "../db/client"

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});
const karla = Karla({
  weight: '700',
  subsets: ['latin'],
});

export default function Home({ notes }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head><nav className={Style.navbar}>
          <h1 className={Style.mainHeading}>📝Your Notes </h1>
          <button className={Style.button}>
            <Link href="/addNote">Add Note</Link>
          </button>
        </nav>
      <main className={[karla.className, Style.container].join(' ')}>
        
        <div className={Style.cardsSection}>
          {notes.map((note) => {
            return (
              <div className={Style.card} key={note.id}>
                <h2 className={Style.cardTitle}>{note.title}</h2>
                <p className={Style.noteContent}>{note.note}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const allNotes = await prisma.note.findMany({orderBy:{modifiedDate:"desc"}});
  // Pass data to the page via props
  return {
    props: {
      notes: 
        JSON.parse(JSON.stringify(allNotes))
      ,
    },
  };
}
